# Generated by Django 3.1.2 on 2020-11-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201031_2044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
