# Generated by Django 3.1.2 on 2020-11-23 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201121_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
