# Generated by Django 3.1.2 on 2020-11-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created',
        ),
    ]
